memgrind: memgrind.o mymalloc.c
  gcc memgrind.o mymalloc.o -0 memgrind
  
memgrind.o: memgrind.c mymalloc.h
  gcc -o memgrind.c
  
mymalloc.o: mymalloc.c mymalloc.h
  gcc -c mymalloc.c
  
clean:
  rm -f memgrind *.o
